#!/usr/bin/env python3
"""
Build high-resolution PPT figures from curated metrics.

Expected inputs generated by collect_ppt_metrics.py:
- outputs/ppt_assets/metrics_summary.json
- outputs/ppt_assets/metrics_table.csv
- outputs/review/n100_vehicle_summary_seed1234.csv

Outputs:
- outputs/ppt_assets/fig_main_results_table.png
- outputs/ppt_assets/fig_type_service_rates.png
- outputs/ppt_assets/fig_type_delay_rates.png
- outputs/ppt_assets/fig_overall_service_delay.png
- outputs/ppt_assets/fig_counts_breakdown.png
- outputs/ppt_assets/fig_vehicle_late_profile_n100.png
- outputs/ppt_assets/fig_eval_risk_overview.png
"""

import argparse
import csv
import json
import os

import matplotlib.pyplot as plt
import numpy as np


plt.rcParams["font.family"] = "Arial"
plt.rcParams["axes.unicode_minus"] = False

COLORS = {
    "primary": "#1f4e79",
    "secondary": "#2b8cbe",
    "passenger": "#1f77b4",
    "cargo": "#2ca25f",
    "risk": "#d62728",
    "muted": "#7f8c8d",
    "bg": "#f7f9fb",
}


def _to_float(v):
    if v is None:
        return None
    s = str(v).strip()
    if s == "":
        return None
    try:
        return float(s)
    except ValueError:
        return None


def load_metrics_table(path):
    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(
                {
                    "graph_size": int(row["graph_size"]),
                    "passenger_orders_total": _to_float(row["passenger_orders_total"]),
                    "cargo_orders_total": _to_float(row["cargo_orders_total"]),
                    "passenger_served_total": _to_float(row["passenger_served_total"]),
                    "cargo_served_total": _to_float(row["cargo_served_total"]),
                    "passenger_late_total": _to_float(row["passenger_late_total"]),
                    "cargo_late_total": _to_float(row["cargo_late_total"]),
                    "passenger_service_rate": _to_float(row["passenger_service_rate"]),
                    "cargo_service_rate": _to_float(row["cargo_service_rate"]),
                    "passenger_delay_rate": _to_float(row["passenger_delay_rate"]),
                    "cargo_delay_rate": _to_float(row["cargo_delay_rate"]),
                    "overall_service_rate": _to_float(row["overall_service_rate"]),
                    "overall_delay_rate": _to_float(row["overall_delay_rate"]),
                    "eval_unfulfilled_rate_mean": _to_float(row["eval_unfulfilled_rate_mean"]),
                    "eval_rejected_rate_mean": _to_float(row["eval_rejected_rate_mean"]),
                }
            )
    rows.sort(key=lambda x: x["graph_size"])
    return rows


def load_vehicle_summary(path):
    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(
                {
                    "vehicle_id": int(row["vehicle_id"]),
                    "serve_count": int(float(row["serve_count"])),
                    "late_count": int(float(row["late_count"])),
                    "max_late_min": _to_float(row.get("max_late_min")) or 0.0,
                }
            )
    return rows


def savefig(path):
    plt.tight_layout()
    plt.savefig(path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close()
    print(f"[done] wrote {path}")


def fig_main_results_table(rows, out_path):
    headers = [
        "N",
        "P Orders",
        "C Orders",
        "P Served",
        "C Served",
        "P Service",
        "C Service",
        "P Delay",
        "C Delay",
    ]
    body = []
    for r in rows:
        body.append(
            [
                f"n{r['graph_size']}",
                int(r["passenger_orders_total"] or 0),
                int(r["cargo_orders_total"] or 0),
                int(r["passenger_served_total"] or 0),
                int(r["cargo_served_total"] or 0),
                f"{100*(r['passenger_service_rate'] or 0):.2f}%",
                f"{100*(r['cargo_service_rate'] or 0):.2f}%",
                f"{100*(r['passenger_delay_rate'] or 0):.2f}%",
                f"{100*(r['cargo_delay_rate'] or 0):.2f}%",
            ]
        )

    fig, ax = plt.subplots(figsize=(12.8, 4.8))
    ax.axis("off")
    tbl = ax.table(cellText=body, colLabels=headers, loc="center", cellLoc="center")
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(11)
    tbl.scale(1, 1.6)

    for (i, j), cell in tbl.get_celld().items():
        if i == 0:
            cell.set_facecolor("#ddebf7")
            cell.set_text_props(weight="bold", color="#1f4e79")
        elif i > 0 and i % 2 == 0:
            cell.set_facecolor("#f7f9fb")

    ax.set_title("Core Metrics by Scale (n25/n50/n100/n200)", fontsize=16, color=COLORS["primary"], pad=16)
    savefig(out_path)


def fig_type_service_rates(rows, out_path):
    n_labels = [f"n{r['graph_size']}" for r in rows]
    p = [100 * (r["passenger_service_rate"] or 0) for r in rows]
    c = [100 * (r["cargo_service_rate"] or 0) for r in rows]

    x = np.arange(len(rows))
    w = 0.35

    fig, ax = plt.subplots(figsize=(10, 5))
    b1 = ax.bar(x - w / 2, p, w, label="Passenger", color=COLORS["passenger"])
    b2 = ax.bar(x + w / 2, c, w, label="Cargo", color=COLORS["cargo"])

    ax.set_ylabel("Service rate (%)")
    ax.set_title("Passenger vs Cargo Service Rate", color=COLORS["primary"], fontsize=15)
    ax.set_xticks(x, n_labels)
    ax.set_ylim(0, 100)
    ax.grid(axis="y", linestyle="--", alpha=0.25)
    ax.legend()

    for bars in (b1, b2):
        for b in bars:
            h = b.get_height()
            ax.annotate(f"{h:.1f}", (b.get_x() + b.get_width() / 2, h), ha="center", va="bottom", fontsize=9)

    savefig(out_path)


def fig_type_delay_rates(rows, out_path):
    n_labels = [f"n{r['graph_size']}" for r in rows]
    p = [100 * (r["passenger_delay_rate"] or 0) for r in rows]
    c = [100 * (r["cargo_delay_rate"] or 0) for r in rows]

    x = np.arange(len(rows))
    w = 0.35

    fig, ax = plt.subplots(figsize=(10, 5))
    b1 = ax.bar(x - w / 2, p, w, label="Passenger", color="#4f81bd")
    b2 = ax.bar(x + w / 2, c, w, label="Cargo", color="#c0504d")

    ax.set_ylabel("Delay rate (%)")
    ax.set_title("Passenger vs Cargo Delay Rate", color=COLORS["primary"], fontsize=15)
    ax.set_xticks(x, n_labels)
    ymax = max(max(c), 1.0) * 1.25
    ax.set_ylim(0, ymax)
    ax.grid(axis="y", linestyle="--", alpha=0.25)
    ax.legend()

    for bars in (b1, b2):
        for b in bars:
            h = b.get_height()
            ax.annotate(f"{h:.1f}", (b.get_x() + b.get_width() / 2, h), ha="center", va="bottom", fontsize=9)

    savefig(out_path)


def fig_overall_service_delay(rows, out_path):
    n_vals = [r["graph_size"] for r in rows]
    service = [100 * (r["overall_service_rate"] or 0) for r in rows]
    delay = [100 * (r["overall_delay_rate"] or 0) for r in rows]

    fig, ax1 = plt.subplots(figsize=(10, 5))
    ax2 = ax1.twinx()

    l1 = ax1.plot(n_vals, service, marker="o", linewidth=2.4, color=COLORS["primary"], label="Overall service rate")
    l2 = ax2.plot(n_vals, delay, marker="s", linewidth=2.0, color=COLORS["risk"], label="Overall delay rate")

    ax1.set_xlabel("Graph size N")
    ax1.set_ylabel("Service rate (%)", color=COLORS["primary"])
    ax2.set_ylabel("Delay rate (%)", color=COLORS["risk"])
    ax1.set_xticks(n_vals)
    ax1.grid(axis="y", linestyle="--", alpha=0.2)

    lines = l1 + l2
    labels = [l.get_label() for l in lines]
    ax1.legend(lines, labels, loc="upper left")
    ax1.set_title("Overall Service/Delay Trend by Scale", fontsize=15, color=COLORS["primary"])

    savefig(out_path)


def fig_counts_breakdown(rows, out_path):
    labels = [f"n{r['graph_size']}" for r in rows]
    x = np.arange(len(rows))
    width = 0.22

    p_orders = [r["passenger_orders_total"] or 0 for r in rows]
    c_orders = [r["cargo_orders_total"] or 0 for r in rows]
    p_served = [r["passenger_served_total"] or 0 for r in rows]
    c_served = [r["cargo_served_total"] or 0 for r in rows]
    p_late = [r["passenger_late_total"] or 0 for r in rows]
    c_late = [r["cargo_late_total"] or 0 for r in rows]

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Orders vs served
    ax = axes[0]
    ax.bar(x - width, p_orders, width, label="Passenger orders", color="#9ecae1")
    ax.bar(x, p_served, width, label="Passenger served", color=COLORS["passenger"])
    ax.bar(x + width, c_served, width, label="Cargo served", color=COLORS["cargo"])
    ax.plot(x + width, c_orders, color="#31a354", marker="o", linestyle="--", label="Cargo orders")
    ax.set_xticks(x, labels)
    ax.set_title("Order and Service Volume")
    ax.grid(axis="y", linestyle="--", alpha=0.2)
    ax.legend(fontsize=8)

    # Late counts
    ax = axes[1]
    ax.bar(x - width / 2, p_late, width, label="Passenger late", color="#6baed6")
    ax.bar(x + width / 2, c_late, width, label="Cargo late", color="#fb6a4a")
    ax.set_xticks(x, labels)
    ax.set_title("Late Delivery Counts")
    ax.grid(axis="y", linestyle="--", alpha=0.2)
    ax.legend(fontsize=8)

    fig.suptitle("Count-level Breakdown", fontsize=15, color=COLORS["primary"])
    savefig(out_path)


def fig_vehicle_late_profile_n100(rows, out_path):
    used = [r for r in rows if r["serve_count"] > 0]
    used.sort(key=lambda r: (r["late_count"], r["serve_count"], r["vehicle_id"]), reverse=True)
    top = used[:12]

    labels = [f"V{r['vehicle_id']}" for r in top]
    late = [r["late_count"] for r in top]
    max_late = [r["max_late_min"] for r in top]

    x = np.arange(len(top))
    fig, ax1 = plt.subplots(figsize=(11, 5))
    ax2 = ax1.twinx()

    b = ax1.bar(x, late, color="#fb6a4a", alpha=0.85, label="Late event count")
    l = ax2.plot(x, max_late, color="#54278f", marker="o", linewidth=2, label="Max late minutes")

    ax1.set_xticks(x, labels)
    ax1.set_ylabel("Late event count")
    ax2.set_ylabel("Max late (min)")
    ax1.set_title("N100 Vehicle-level Delay Profile (Top late vehicles)", color=COLORS["primary"], fontsize=14)
    ax1.grid(axis="y", linestyle="--", alpha=0.2)

    lines = [b, l[0]]
    ax1.legend(lines, ["Late event count", "Max late minutes"], loc="upper right")

    savefig(out_path)


def fig_eval_risk_overview(rows, out_path):
    n_labels = [f"n{r['graph_size']}" for r in rows]
    rej = [100 * (r["eval_rejected_rate_mean"] or 0) for r in rows]
    unf = [100 * (r["eval_unfulfilled_rate_mean"] or 0) for r in rows]

    x = np.arange(len(rows))
    width = 0.35

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.bar(x - width / 2, rej, width, label="Rejected rate", color="#9e9ac8")
    ax.bar(x + width / 2, unf, width, label="Unfulfilled rate", color="#e34a33")

    ax.set_xticks(x, n_labels)
    ax.set_ylabel("Rate (%)")
    ax.set_title("Operational Risk Overview from Eval500", color=COLORS["primary"], fontsize=15)
    ax.grid(axis="y", linestyle="--", alpha=0.25)
    ax.legend()

    savefig(out_path)


def parse_args():
    p = argparse.ArgumentParser(description="Build PPT figures from curated metrics")
    p.add_argument("--metrics-table", default="outputs/ppt_assets/metrics_table.csv")
    p.add_argument("--vehicle-summary", default="outputs/review/n100_vehicle_summary_seed1234.csv")
    p.add_argument("--out-dir", default="outputs/ppt_assets")
    return p.parse_args()


def main():
    args = parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    rows = load_metrics_table(args.metrics_table)
    vehicle_rows = load_vehicle_summary(args.vehicle_summary)

    fig_main_results_table(rows, os.path.join(args.out_dir, "fig_main_results_table.png"))
    fig_type_service_rates(rows, os.path.join(args.out_dir, "fig_type_service_rates.png"))
    fig_type_delay_rates(rows, os.path.join(args.out_dir, "fig_type_delay_rates.png"))
    fig_overall_service_delay(rows, os.path.join(args.out_dir, "fig_overall_service_delay.png"))
    fig_counts_breakdown(rows, os.path.join(args.out_dir, "fig_counts_breakdown.png"))
    fig_vehicle_late_profile_n100(vehicle_rows, os.path.join(args.out_dir, "fig_vehicle_late_profile_n100.png"))
    fig_eval_risk_overview(rows, os.path.join(args.out_dir, "fig_eval_risk_overview.png"))


if __name__ == "__main__":
    main()
